live_config_reload = true

[cursor]
style = "Block"

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "Buttonless"
dynamic_title = true
option_as_alt = "Both"
dynamic_padding = true
startup_mode = "Maximized"
opacity = 1.0
dimensions = { columns = 200, lines = 60 }
padding = { x = 4, y = 4 }

