import = ["~/.config/alacritty/everforest.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 20.4

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "Buttonless"
option_as_alt = "Both"
startup_mode = "Maximized"
opacity = 0.8
padding = { y = 5 }
