format = """$directory$git_branch$git_status$character"""
right_format = """$all"""
palette = "wintersakura"

[directory]
style = "teal"
read_only = " 󰌾"
truncation_length = 1
truncate_to_repo = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](purple)"

[git_branch]
style = "peach"

[git_status]
staged = '[++\($count\)](green)'
format = '([$all_status$ahead_behind]($style) )'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
disabled = true

[cmd_duration]
format = "[$duration ]($style)"
style = "yellow"

[fill]
symbol = " "

[aws]
disabled = true

[gcloud]
disabled = true

[lua]
symbol = "󰢱 "
style = "lavender"
format = '[$symbol]($style)'

[golang]
symbol = " "
style = "teal"
format = '[$symbol]($style)'

[bun]
format = '[bun 🍔 $version](bold) '

[deno]
format = '[$symbol $version](bold) '

[nodejs]
format = "[$symbol($version )]($style)"
detect_extensions = []

[docker_context]
disabled = true

[palettes.wintersakura]
rosewater = "#ECEFF4"  # Corresponds to Nord's Snow Storm 2
flamingo = "#E5E9F0"   # Snow Storm 1
pink = "#D8DEE9"       # Snow Storm 0
mauve = "#B48EAD"      # Aurora - Purple
red = "#BF616A"        # Aurora - Red
maroon = "#D08770"     # Aurora - Orange
peach = "#EBCB8B"      # Aurora - Yellow
yellow = "#EBCB8B"     # Aurora - Yellow
green = "#A3BE8C"      # Aurora - Green
teal = "#88C0D0"       # Frost - Teal
sky = "#8FBCBB"        # Frost - Cyan
sapphire = "#5E81AC"   # Frost - Blue
blue = "#81A1C1"       # Frost - Blue
lavender = "#B48EAD"   # Aurora - Purple
text = "#D8DEE9"       # Snow Storm 0
subtext1 = "#E5E9F0"   # Snow Storm 1
subtext0 = "#ECEFF4"   # Snow Storm 2
overlay2 = "#4C566A"   # Polar Night - Darkest Grey
overlay1 = "#3B4252"   # Polar Night - Medium Grey
overlay0 = "#2E3440"   # Polar Night - Light Grey
surface2 = "#434C5E"   # Polar Night - Deep Grey
surface1 = "#3B4252"   # Polar Night - Medium Grey
surface0 = "#2E3440"   # Polar Night - Light Grey
base = "#2E3440"       # Polar Night - Light Grey
mantle = "#3B4252"     # Polar Night - Medium Grey
crust = "#434C5E"      # Polar Night - Deep Grey
