format = """$directory$git_branch$git_status$character"""
right_format = """$all"""
palette = "catppuccin_mocha"

[directory]
style = "teal"
read_only = " 󰌾"
truncation_length = 1
truncate_to_repo = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](purple)"

[git_branch]
style = "peach"

[git_status]
staged = '[++\($count\)](green)'
format = '([$all_status$ahead_behind]($style) )'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
disabled = true

[cmd_duration]
format = "[$duration ]($style)"
style = "yellow"

[fill]
symbol = " "

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = " "

[lua]
symbol = "󰢱 "
style = "lavender"
format = '[$symbol]($style)'

[golang]
symbol = " "
style = "cyan"
format = '[$symbol]($style)'

[bun]
format = '[bun 🍔 $version](bold) '

[nodejs]
format = "[$symbol($version )]($style)"

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
